"""
Django settings for CNCTOOLS project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Import danych poufnych z pass_file.py
try:
    from .pass_file import (
        DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT,
        EMAIL_HOST, EMAIL_PORT, EMAIL_USE_SSL, EMAIL_USE_TLS,
        EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, DEFAULT_FROM_EMAIL,
        EMAIL_TEST_ADDRESS, EMAIL_DW
    )
except ImportError:
    raise ImportError(
        "Brak pliku pass_file.py! Skopiuj pass_file.py.example i uzupełnij danymi."
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m!-epurjl0s-y60esc746trodx_hq3k+8+=s@_mo_3&f#05f*$'

# SECURITY WARNING: don't run with debug turned on in production!
# Używa zmiennej środowiskowej DJANGO_DEBUG (domyślnie True dla developmentu)
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS = ['*']  # Akceptuje polaczenia z wszystkich adresow (tylko dla DEBUG=True!)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'TOOLS',
    'inertia',
    'django_vite',
    'pwa',
]


REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serwowanie plików statycznych w produkcji
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'inertia.middleware.InertiaMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CNCTOOLS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'CNCTOOLS.context_processors.vite_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'CNCTOOLS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pl'
TIME_ZONE = 'Europe/Warsaw'
USE_I18N = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Tutaj collectstatic zbiera pliki (produkcja)

STATICFILES_DIRS = [
    BASE_DIR / 'static_dev',  # ← ZMIENIONE z 'static' na 'static_dev'
    BASE_DIR / 'resources',
]

# Whitenoise - serwowanie plików statycznych w produkcji
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'




# Konfiguracja dla plików wgrywanych przez użytkownika
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Katalog z plikami instalacyjnymi (certyfikat SSL, CardReader.exe)
# Dostępne publicznie przez /install/
INSTALL_ROOT = BASE_DIR / 'install'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'redirect_after_login'


# ========== KONFIGURACJA EMAIL ==========
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Dane EMAIL_HOST, EMAIL_PORT, EMAIL_USE_SSL, EMAIL_USE_TLS,
# EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, DEFAULT_FROM_EMAIL, EMAIL_TEST_ADDRESS
# są importowane z pass_file.py


INFO_PROGRAM = [
    {
        'WERSJA'     : '0.92.0g',
        'MODYFIKACJA': '14.01.2026r.',
        'FIRMA'      : 'EDATABIT',
        'AUTOR'      : 'Jarosław Stróżyk',
        'EMAIL'      : 'mailto:biuro@edatabit.pl',
        'NEMAIL'     : 'biuro@edatabit.pl',
        'TEL'        : '+48 791-648-417',
    },
]


INERTIA_LAYOUT = 'app.html'
INERTIA_SSR_ENABLED = False

# Django Vite - konfiguracja dla Vite 5+
DJANGO_VITE = {
    "default": {
        "dev_mode": DEBUG,
        "dev_server_host": "0.0.0.0",
        "dev_server_port": 5173,
        "static_url_prefix": "dist",
        "manifest_path": BASE_DIR / "static_dev" / "dist" / ".vite" / "manifest.json",
    }
}


# Inertia shared data (dostępne we wszystkich komponentach przez $page.props)
INERTIA_SHARE = {
    'auth': lambda request: {
        'user': {
            'username': request.user.username,
            'email': request.user.email,
        } if request.user.is_authenticated else None
    }
}


# ========== KONFIGURACJA PWA ==========
PWA_APP_NAME = 'CNC Tools'
PWA_APP_DESCRIPTION = 'System zarzadzania narzedziami CNC'
PWA_APP_THEME_COLOR = '#1f2937'
PWA_APP_BACKGROUND_COLOR = '#111827'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_LANG = 'pl-PL'
PWA_APP_DIR = 'ltr'

# Ikony PWA (rozne rozmiary)
PWA_APP_ICONS = [
    {
        'src': '/static/images/icons/icon-72x72.png',
        'sizes': '72x72',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-96x96.png',
        'sizes': '96x96',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-128x128.png',
        'sizes': '128x128',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-144x144.png',
        'sizes': '144x144',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-152x152.png',
        'sizes': '152x152',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-192x192.png',
        'sizes': '192x192',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-384x384.png',
        'sizes': '384x384',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-512x512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'any maskable'
    }
]

# Splash screens - opcjonalne (zakomentowane)
# PWA_APP_SPLASH_SCREEN = []

# Service Worker
PWA_SERVICE_WORKER_PATH = BASE_DIR / 'static_dev' / 'serviceworker.js'
