"""
Django settings for CNCTOOLS project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Import danych poufnych z pass_file.py
try:
    from .pass_file import (
        DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT,
        EMAIL_HOST, EMAIL_PORT, EMAIL_USE_SSL, EMAIL_USE_TLS,
        EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, DEFAULT_FROM_EMAIL,
        EMAIL_TEST_ADDRESS, EMAIL_DW
    )
except ImportError:
    raise ImportError(
        "Brak pliku pass_file.py! Skopiuj pass_file.py.example i uzupełnij danymi."
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m!-epurjl0s-y60esc746trodx_hq3k+8+=s@_mo_3&f#05f*$'

# SECURITY WARNING: don't run with debug turned on in production!
# Używa zmiennej środowiskowej DJANGO_DEBUG (domyślnie True dla developmentu)
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS = ['*']  # Akceptuje polaczenia z wszystkich adresow (tylko dla DEBUG=True!)


# Dokumenty PDF - wersja i data (ręcznie zmieniane w razie potrzeby)
# Karta zapotrzebowania
PDF_ZAPOTRZEBOWANIE_WERSJA = 2
PDF_ZAPOTRZEBOWANIE_DATA = '2026-01-22'

# Karta uszkodzenia
PDF_USZKODZENIE_WERSJA = 1
PDF_USZKODZENIE_DATA = '2026-02-05'

# Logi
PDF_LOGI_WERSJA = 1
PDF_LOGI_DATA = '2026-01-30'

# Lista uszkodzeń
PDF_LISTA_USZKODZEN_WERSJA = 1
PDF_LISTA_USZKODZEN_DATA = '2026-02-05'

# Inwentura startowa
PDF_INWENTURA_WERSJA = 1
PDF_INWENTURA_DATA = '2026-02-07'


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Musi być PRZED django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'TOOLS',
    'inertia',
    'django_vite',
    'pwa',
]


REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serwowanie plików statycznych w produkcji
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'inertia.middleware.InertiaMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CNCTOOLS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'CNCTOOLS.context_processors.vite_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'CNCTOOLS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pl'
TIME_ZONE = 'Europe/Warsaw'
USE_I18N = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Tutaj collectstatic zbiera pliki (produkcja)

STATICFILES_DIRS = [
    BASE_DIR / 'static_dev',  # ← ZMIENIONE z 'static' na 'static_dev'
    BASE_DIR / 'resources',
]

# Whitenoise - serwowanie plików statycznych w produkcji
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'




# Konfiguracja dla plików wgrywanych przez użytkownika
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Katalog z plikami instalacyjnymi (certyfikat SSL, CardReader.exe)
# Dostępne publicznie przez /install/
INSTALL_ROOT = BASE_DIR / 'install'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'redirect_after_login'


# ========== KONFIGURACJA EMAIL ==========
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Dane EMAIL_HOST, EMAIL_PORT, EMAIL_USE_SSL, EMAIL_USE_TLS,
# EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, DEFAULT_FROM_EMAIL, EMAIL_TEST_ADDRESS
# są importowane z pass_file.py


INFO_PROGRAM = [
    {
        'WERSJA'     : '0.99.0g',
        'MODYFIKACJA': '22.02.2026r.',
        'FIRMA'      : 'EDATABIT',
        'AUTOR'      : 'Jarosław Stróżyk',
        'EMAIL'      : 'mailto:biuro@edatabit.pl',
        'NEMAIL'     : 'biuro@edatabit.pl',
        'TEL'        : '+48 791-648-417',
    },
]


INERTIA_LAYOUT = 'app.html'
INERTIA_SSR_ENABLED = False

# Django Vite - konfiguracja dla Vite 5+
DJANGO_VITE = {
    "default": {
        "dev_mode": DEBUG,
        "dev_server_host": "0.0.0.0",
        "dev_server_port": 5173,
        "static_url_prefix": "dist",
        "manifest_path": BASE_DIR / "static_dev" / "dist" / ".vite" / "manifest.json",
    }
}


# Inertia shared data (dostępne we wszystkich komponentach przez $page.props)
INERTIA_SHARE = {
    'auth': lambda request: {
        'user': {
            'username': request.user.username,
            'email': request.user.email,
        } if request.user.is_authenticated else None
    }
}


# ========== KONFIGURACJA PWA ==========
PWA_APP_NAME = 'CNC Tools'
PWA_APP_DESCRIPTION = 'System zarzadzania narzedziami CNC'
PWA_APP_THEME_COLOR = '#1f2937'
PWA_APP_BACKGROUND_COLOR = '#111827'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_LANG = 'pl-PL'
PWA_APP_DIR = 'ltr'

# Ikony PWA (rozne rozmiary)
PWA_APP_ICONS = [
    {
        'src': '/static/images/icons/icon-72x72.png',
        'sizes': '72x72',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-96x96.png',
        'sizes': '96x96',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-128x128.png',
        'sizes': '128x128',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-144x144.png',
        'sizes': '144x144',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-152x152.png',
        'sizes': '152x152',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-192x192.png',
        'sizes': '192x192',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-384x384.png',
        'sizes': '384x384',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-512x512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'any maskable'
    }
]

# Splash screens - opcjonalne (zakomentowane)
# PWA_APP_SPLASH_SCREEN = []

# Service Worker
PWA_SERVICE_WORKER_PATH = BASE_DIR / 'static_dev' / 'serviceworker.js'


# ========== KONFIGURACJA JAZZMIN (Django Admin) ==========
JAZZMIN_SETTINGS = {
    # Tytuł w oknie przeglądarki
    "site_title": "CNC Tools Admin",

    # Tytuł na ekranie logowania
    "site_header": "CNC Tools",

    # Tytuł w menu bocznym
    "site_brand": "CNC Tools",

    # Logo (opcjonalne) - w sidebar
    "site_logo": "images/icons/icon-72x72.png",

    # Logo na ekranie logowania (None = brak logo)
    "login_logo": None,

    # Ukryj logo na ekranie logowania
    "login_logo_dark": None,

    # CSS classes dla logo
    "site_logo_classes": "img-circle",

    # Ikona favicon
    "site_icon": "images/icons/icon-72x72.png",

    # Custom CSS - naprawki stylów
    "custom_css": "css/jazzmin-fixes.css",

    # Link do powrotu do aplikacji
    "welcome_sign": "Panel administracyjny CNC Tools",

    # Copyright
    "copyright": "EDATABIT - Jarosław Stróżyk",

    # Użytkownik w prawym górnym rogu
    "user_avatar": None,

    # Linki w topbar
    "topmenu_links": [
        {"name": "Aplikacja", "url": "/", "new_window": False},
        {"name": "API", "url": "/api/", "new_window": True},
    ],

    # Ukryj modele w menu
    "hide_models": [],

    # Kolejność aplikacji w menu
    "order_with_respect_to": ["auth", "TOOLS"],

    # Ikony dla modeli (Font Awesome 5)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "TOOLS.Pracownik": "fas fa-id-card",
        "TOOLS.NarzedzieMagazynowe": "fas fa-tools",
        "TOOLS.EgzemplarzNarzedzia": "fas fa-wrench",
        "TOOLS.HistoriaUzyciaNarzedzia": "fas fa-history",
        "TOOLS.Kategoria": "fas fa-folder",
        "TOOLS.Podkategoria": "fas fa-folder-open",
        "TOOLS.Lokalizacja": "fas fa-map-marker-alt",
        "TOOLS.Maszyna": "fas fa-industry",
        "TOOLS.Dostawca": "fas fa-truck",
        "TOOLS.Zamowienie": "fas fa-shopping-cart",
        "TOOLS.FakturaZakupu": "fas fa-file-invoice-dollar",
        "TOOLS.Uszkodzenie": "fas fa-exclamation-triangle",
    },

    # Domyślna ikona
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    # Powiązane modele (show/hide)
    "related_modal_active": True,

    # UI Tweaks
    "show_sidebar": True,
    "navigation_expanded": True,
    "show_ui_builder": False,

    # Zmień tekst "Django administration"
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
    },
}

# Jazzmin UI customizer - ciemny motyw
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark navbar-gray-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
