# Generated by Django 4.2.23 on 2025-10-07 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dostawca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_firmy', models.CharField(max_length=200, verbose_name='Nazwa firmy')),
                ('kod_dostawcy', models.CharField(max_length=50, unique=True, verbose_name='Kod dostawcy')),
            ],
            options={
                'verbose_name': 'Dostawca',
                'verbose_name_plural': 'Dostawcy',
            },
        ),
        migrations.CreateModel(
            name='EgzemplarzNarzedzia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stan', models.CharField(choices=[('nowe', 'Nowe'), ('uzywane', 'Używane (dostępne)'), ('w_uzyciu', 'W użyciu'), ('uszkodzone', 'Uszkodzone')], default='nowe', max_length=10, verbose_name='Stan')),
            ],
            options={
                'verbose_name': 'Egzemplarz Narzędzia',
                'verbose_name_plural': 'Egzemplarze Narzędzi',
            },
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True, verbose_name='Nazwa kategorii')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Maszyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True, verbose_name='Nazwa maszyny')),
            ],
            options={
                'verbose_name': 'Maszyna',
                'verbose_name_plural': 'Maszyny',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Narzedzie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=255, verbose_name='Opis / Specyfikacja')),
                ('numer_katalogowy', models.CharField(max_length=100, unique=True, verbose_name='Numer katalogowy')),
                ('dostawca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TOOLS.dostawca', verbose_name='Dostawca')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narzedzia', to='TOOLS.kategoria', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Typ Narzędzia',
                'verbose_name_plural': 'Typy Narzędzi',
            },
        ),
        migrations.CreateModel(
            name='Lokalizacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szafa', models.CharField(max_length=50, verbose_name='Szafa')),
                ('kolumna', models.CharField(max_length=50, verbose_name='Kolumna')),
                ('polka', models.CharField(max_length=50, verbose_name='Półka')),
            ],
            options={
                'verbose_name': 'Lokalizacja',
                'verbose_name_plural': 'Lokalizacje',
                'unique_together': {('szafa', 'kolumna', 'polka')},
            },
        ),
        migrations.CreateModel(
            name='HistoriaUzycia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wydania', models.DateTimeField(auto_now_add=True, verbose_name='Data wydania')),
                ('data_zwrotu', models.DateTimeField(blank=True, null=True, verbose_name='Data zwrotu')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
                ('egzemplarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_uzycia', to='TOOLS.egzemplarznarzedzia', verbose_name='Egzemplarz')),
                ('maszyna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TOOLS.maszyna', verbose_name='Maszyna')),
            ],
            options={
                'verbose_name': 'Historia użycia',
                'verbose_name_plural': 'Historia użycia',
                'ordering': ['-data_wydania'],
            },
        ),
        migrations.AddField(
            model_name='egzemplarznarzedzia',
            name='lokalizacja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TOOLS.lokalizacja', verbose_name='Lokalizacja'),
        ),
        migrations.AddField(
            model_name='egzemplarznarzedzia',
            name='narzedzie_typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egzemplarze', to='TOOLS.narzedzie', verbose_name='Typ narzędzia'),
        ),
    ]
