# Generated by Django 4.2.23 on 2025-10-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egzemplarznarzedzia',
            name='stan',
            field=models.CharField(choices=[('nowe', 'Nowe'), ('uzywane', 'Używane'), ('uszkodzone', 'Uszkodzone')], default='nowe', max_length=10, verbose_name='Stan'),
        ),
        migrations.AlterField(
            model_name='narzedzie',
            name='numer_katalogowy',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Numer katalogowy'),
        ),
    ]
