# Generated by Django 4.2.23 on 2025-10-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0002_alter_egzemplarznarzedzia_stan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoria',
            name='obraz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nazwa pliku obrazka (w static/kategorie/)'),
        ),
    ]
