# Generated by Django 4.2.23 on 2025-10-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0003_kategoria_obraz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoria',
            name='obraz',
            field=models.ImageField(blank=True, null=True, upload_to='kategorie/', verbose_name='Obrazek kategorii'),
        ),
    ]
