# Generated by Django 4.2.23 on 2025-10-16 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0004_alter_kategoria_obraz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egzemplarznarzedzia',
            options={'ordering': ['-data_modyfikacji'], 'verbose_name': 'Egzemplarz Narzędzia', 'verbose_name_plural': 'Egzemplarze Narzędzi'},
        ),
        migrations.AddField(
            model_name='egzemplarznarzedzia',
            name='data_modyfikacji',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data modyfikacji'),
        ),
        migrations.AddField(
            model_name='egzemplarznarzedzia',
            name='data_utworzenia',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia'),
        ),
    ]
