# Generated by Django 4.2.23 on 2025-10-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0005_alter_egzemplarznarzedzia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egzemplarznarzedzia',
            name='data_modyfikacji',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='egzemplarznarzedzia',
            name='data_utworzenia',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
    ]
