# Generated by Django 4.2.23 on 2025-10-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0006_alter_egzemplarznarzedzia_data_modyfikacji_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uszkodzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_narzedzia', models.CharField(max_length=255, verbose_name='Opis narzędzia')),
                ('numer_katalogowy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numer katalogowy')),
                ('kategoria_narzedzia', models.CharField(max_length=100, verbose_name='Kategoria')),
                ('id_egzemplarza', models.PositiveIntegerField(verbose_name='ID usuniętego egzemplarza')),
                ('maszyna_uszkodzenia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Maszyna (ostatnie użycie)')),
                ('data_uszkodzenia', models.DateTimeField(verbose_name='Data zwrotu jako uszkodzone')),
                ('data_archiwizacji', models.DateTimeField(auto_now_add=True, verbose_name='Data archiwizacji')),
            ],
            options={
                'verbose_name': 'Uszkodzenie (Archiwum)',
                'verbose_name_plural': 'Uszkodzenia (Archiwum)',
                'ordering': ['-data_archiwizacji'],
            },
        ),
    ]
