# Generated by Django 4.2.23 on 2025-10-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0007_uszkodzenie'),
    ]

    operations = [
        migrations.AddField(
            model_name='uszkodzenie',
            name='data_utworzenia_egzemplarza',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data utworzenia egzemplarza'),
        ),
        migrations.AddField(
            model_name='uszkodzenie',
            name='ostatnia_lokalizacja',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ostatnia lokalizacja'),
        ),
    ]
