# Generated by Django 4.2.23 on 2025-10-16 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0008_uszkodzenie_data_utworzenia_egzemplarza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_faktury', models.CharField(max_length=100, unique=True, verbose_name='Numer faktury')),
                ('data_wystawienia', models.DateField(verbose_name='Data wystawienia')),
                ('plik', models.FileField(upload_to='faktury/', verbose_name='Plik z fakturą (PDF, obraz)')),
                ('dostawca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TOOLS.dostawca', verbose_name='Dostawca')),
                ('narzedzia', models.ManyToManyField(blank=True, related_name='faktury', to='TOOLS.narzedzie', verbose_name='Powiązane narzędzia')),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Faktury',
                'ordering': ['-data_wystawienia'],
            },
        ),
    ]
