# Generated by Django 4.2.23 on 2025-10-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0009_faktura'),
    ]

    operations = [
        migrations.AddField(
            model_name='narzedzie',
            name='limit_minimalny',
            field=models.PositiveIntegerField(default=0, verbose_name='Limit minimalny'),
        ),
    ]
