# Generated by Django 4.2.23 on 2025-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0010_narzedzie_limit_minimalny'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dostawca',
            options={'ordering': ['nazwa_firmy'], 'verbose_name': 'Dostawca', 'verbose_name_plural': 'Dostawcy'},
        ),
        migrations.AddField(
            model_name='dostawca',
            name='adres',
            field=models.TextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='dostawca',
            name='data_modyfikacji',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AddField(
            model_name='dostawca',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='dostawca',
            name='telefon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
    ]
