# Generated by Django 4.2.23 on 2025-10-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0011_alter_dostawca_options_dostawca_adres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dostawca',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIP'),
        ),
    ]
