# Generated by Django 4.2.23 on 2025-10-25 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0012_dostawca_nip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategoria',
            name='obraz',
        ),
        migrations.RemoveField(
            model_name='narzedzie',
            name='kategoria',
        ),
        migrations.AddField(
            model_name='narzedzie',
            name='obraz',
            field=models.ImageField(blank=True, null=True, upload_to='narzedzia/', verbose_name='Obraz narzędzia'),
        ),
        migrations.CreateModel(
            name='Podkategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa podkategorii')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podkategorie', to='TOOLS.kategoria', verbose_name='Kategoria nadrzędna')),
            ],
            options={
                'verbose_name': 'Podkategoria',
                'verbose_name_plural': 'Podkategorie',
                'ordering': ['kategoria__nazwa', 'nazwa'],
                'unique_together': {('kategoria', 'nazwa')},
            },
        ),
        migrations.AddField(
            model_name='narzedzie',
            name='podkategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narzedzia', to='TOOLS.podkategoria', verbose_name='Podkategoria'),
        ),
    ]
