# Generated by Django 4.2.23 on 2025-10-25 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0013_remove_kategoria_obraz_remove_narzedzie_kategoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karta', models.CharField(max_length=50, unique=True, verbose_name='Numer karty')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('imie', models.CharField(max_length=100, verbose_name='Imię')),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
                'ordering': ['nazwisko', 'imie'],
            },
        ),
        migrations.AddField(
            model_name='historiauzycia',
            name='pracownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historia_uzycia', to='TOOLS.pracownik', verbose_name='Pracownik'),
        ),
    ]
