# Generated by Django 4.2.23 on 2025-10-26 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0014_pracownik_historiauzycia_pracownik'),
    ]

    operations = [
        migrations.AddField(
            model_name='egzemplarznarzedzia',
            name='faktura_zakupu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egzemplarze', to='TOOLS.faktura', verbose_name='Faktura zakupu'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='rozliczone',
            field=models.BooleanField(default=False, verbose_name='Rozliczona'),
        ),
    ]
