# Generated by Django 4.2.23 on 2025-10-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0015_egzemplarznarzedzia_faktura_zakupu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='plik',
            field=models.FileField(blank=True, null=True, upload_to='faktury/', verbose_name='Plik z fakturą (PDF, obraz)'),
        ),
    ]
