# Generated by Django 4.2.23 on 2025-10-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0016_alter_faktura_plik'),
    ]

    operations = [
        migrations.AddField(
            model_name='uszkodzenie',
            name='ostatni_pracownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uszkodzenia', to='TOOLS.pracownik', verbose_name='Ostatni użytkownik'),
        ),
    ]
