# Generated by Django 4.2.23 on 2025-11-06 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0017_uszkodzenie_ostatni_pracownik'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakturaZakupu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_faktury', models.CharField(max_length=100, unique=True)),
                ('data_wystawienia', models.DateField()),
                ('plik', models.FileField(blank=True, null=True, upload_to='faktury/')),
                ('rozliczone', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Faktury zakupu',
                'ordering': ['-data_wystawienia'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaUzyciaNarzedzia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wydania', models.DateTimeField(auto_now_add=True)),
                ('data_zwrotu', models.DateTimeField(blank=True, null=True)),
                ('uwagi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Historia użycia narzędzi',
                'ordering': ['-data_wydania'],
            },
        ),
        migrations.CreateModel(
            name='NarzedzieMagazynowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField()),
                ('numer_katalogowy', models.CharField(blank=True, max_length=100, null=True)),
                ('obraz', models.ImageField(blank=True, null=True, upload_to='narzedzia/')),
                ('stan_minimalny', models.PositiveIntegerField(default=5)),
                ('stan_maksymalny', models.PositiveIntegerField(default=20)),
            ],
            options={
                'verbose_name_plural': 'Narzędzia magazynowe',
                'ordering': ['podkategoria__kategoria__nazwa', 'podkategoria__nazwa', 'opis'],
            },
        ),
        migrations.CreateModel(
            name='PozycjaRealizacji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_przyjeta', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Pozycje realizacji',
                'ordering': ['realizacja', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PozycjaZamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_zamowiona', models.PositiveIntegerField()),
                ('jednostka', models.CharField(choices=[('szt', 'Sztuka'), ('kompl', 'Komplet')], default='szt', max_length=10)),
                ('ilosc_w_komplecie', models.PositiveIntegerField(default=1)),
                ('cena_jednostkowa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ilosc_dostarczona', models.PositiveIntegerField(default=0)),
                ('zrealizowane', models.BooleanField(default=False)),
                ('narzedzie_typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pozycje_zamowien', to='TOOLS.narzedziemagazynowe')),
            ],
            options={
                'verbose_name_plural': 'Pozycje zamówień',
                'ordering': ['zamowienie', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RealizacjaZamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacji', models.DateTimeField(auto_now_add=True)),
                ('uwagi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Realizacje zamówień',
                'ordering': ['-data_realizacji'],
            },
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=50, unique=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_wyslania', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Wersja robocza'), ('verified', 'Zweryfikowane'), ('sent', 'Wysłane'), ('partially_received', 'Częściowo odebrane'), ('completed', 'Zrealizowane')], default='draft', max_length=20)),
                ('uwagi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Zamówienia',
                'ordering': ['-data_utworzenia'],
            },
        ),
        migrations.RemoveField(
            model_name='faktura',
            name='dostawca',
        ),
        migrations.RemoveField(
            model_name='faktura',
            name='narzedzia',
        ),
        migrations.RemoveField(
            model_name='narzedzie',
            name='dostawca',
        ),
        migrations.RemoveField(
            model_name='narzedzie',
            name='podkategoria',
        ),
        migrations.AlterModelOptions(
            name='dostawca',
            options={'ordering': ['nazwa_firmy'], 'verbose_name_plural': 'Dostawcy'},
        ),
        migrations.AlterModelOptions(
            name='egzemplarznarzedzia',
            options={'ordering': ['-data_zakupu'], 'verbose_name_plural': 'Egzemplarze narzędzi'},
        ),
        migrations.AlterModelOptions(
            name='kategoria',
            options={'ordering': ['nazwa'], 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='lokalizacja',
            options={'ordering': ['szafa', 'kolumna', 'polka'], 'verbose_name_plural': 'Lokalizacje'},
        ),
        migrations.AlterModelOptions(
            name='maszyna',
            options={'ordering': ['nazwa'], 'verbose_name_plural': 'Maszyny'},
        ),
        migrations.AlterModelOptions(
            name='podkategoria',
            options={'ordering': ['kategoria__nazwa', 'nazwa'], 'verbose_name_plural': 'Podkategorie'},
        ),
        migrations.AlterModelOptions(
            name='pracownik',
            options={'ordering': ['nazwisko', 'imie'], 'verbose_name_plural': 'Pracownicy'},
        ),
        migrations.AlterModelOptions(
            name='uszkodzenie',
            options={'ordering': ['-data_uszkodzenia'], 'verbose_name_plural': 'Uszkodzenia'},
        ),
        migrations.AlterUniqueTogether(
            name='podkategoria',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dostawca',
            name='data_modyfikacji',
        ),
        migrations.RemoveField(
            model_name='egzemplarznarzedzia',
            name='data_utworzenia',
        ),
        migrations.RemoveField(
            model_name='uszkodzenie',
            name='data_archiwizacji',
        ),
        migrations.RemoveField(
            model_name='uszkodzenie',
            name='data_utworzenia_egzemplarza',
        ),
        migrations.RemoveField(
            model_name='uszkodzenie',
            name='id_egzemplarza',
        ),
        migrations.RemoveField(
            model_name='uszkodzenie',
            name='kategoria_narzedzia',
        ),
        migrations.RemoveField(
            model_name='uszkodzenie',
            name='maszyna_uszkodzenia',
        ),
        migrations.RemoveField(
            model_name='uszkodzenie',
            name='numer_katalogowy',
        ),
        migrations.RemoveField(
            model_name='uszkodzenie',
            name='opis_narzedzia',
        ),
        migrations.RemoveField(
            model_name='uszkodzenie',
            name='ostatni_pracownik',
        ),
        migrations.RemoveField(
            model_name='uszkodzenie',
            name='ostatnia_lokalizacja',
        ),
        migrations.AddField(
            model_name='egzemplarznarzedzia',
            name='data_zakupu',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='egzemplarznarzedzia',
            name='ilosc_w_komplecie',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='egzemplarznarzedzia',
            name='jednostka',
            field=models.CharField(choices=[('szt', 'Sztuka'), ('kompl', 'Komplet')], default='szt', max_length=10),
        ),
        migrations.AddField(
            model_name='uszkodzenie',
            name='egzemplarz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uszkodzenia', to='TOOLS.egzemplarznarzedzia'),
        ),
        migrations.AddField(
            model_name='uszkodzenie',
            name='opis_uszkodzenia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='uszkodzenie',
            name='pracownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zgloszone_uszkodzenia', to='TOOLS.pracownik'),
        ),
        migrations.AlterField(
            model_name='dostawca',
            name='adres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dostawca',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dostawca',
            name='kod_dostawcy',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dostawca',
            name='nazwa_firmy',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dostawca',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dostawca',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='egzemplarznarzedzia',
            name='data_modyfikacji',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='egzemplarznarzedzia',
            name='lokalizacja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egzemplarze', to='TOOLS.lokalizacja'),
        ),
        migrations.AlterField(
            model_name='egzemplarznarzedzia',
            name='stan',
            field=models.CharField(choices=[('nowe', 'Nowe'), ('uzywane', 'Używane'), ('uszkodzone', 'Uszkodzone')], default='nowe', max_length=20),
        ),
        migrations.AlterField(
            model_name='kategoria',
            name='nazwa',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lokalizacja',
            name='kolumna',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lokalizacja',
            name='polka',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lokalizacja',
            name='szafa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maszyna',
            name='nazwa',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='podkategoria',
            name='kategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podkategorie', to='TOOLS.kategoria'),
        ),
        migrations.AlterField(
            model_name='podkategoria',
            name='nazwa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='imie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='karta',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='nazwisko',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uszkodzenie',
            name='data_uszkodzenia',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='podkategoria',
            unique_together={('nazwa', 'kategoria')},
        ),
        migrations.DeleteModel(
            name='HistoriaUzycia',
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='dostawca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zamowienia', to='TOOLS.dostawca'),
        ),
        migrations.AddField(
            model_name='realizacjazamowienia',
            name='lokalizacja_domyslna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realizacje_zamowien', to='TOOLS.lokalizacja'),
        ),
        migrations.AddField(
            model_name='realizacjazamowienia',
            name='zamowienie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizacje', to='TOOLS.zamowienie'),
        ),
        migrations.AddField(
            model_name='pozycjazamowienia',
            name='zamowienie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozycje', to='TOOLS.zamowienie'),
        ),
        migrations.AddField(
            model_name='pozycjarealizacji',
            name='lokalizacja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pozycje_realizacji', to='TOOLS.lokalizacja'),
        ),
        migrations.AddField(
            model_name='pozycjarealizacji',
            name='pozycja_zamowienia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizacje_pozycji', to='TOOLS.pozycjazamowienia'),
        ),
        migrations.AddField(
            model_name='pozycjarealizacji',
            name='realizacja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozycje', to='TOOLS.realizacjazamowienia'),
        ),
        migrations.AddField(
            model_name='narzedziemagazynowe',
            name='domyslna_lokalizacja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narzedzia_domyslne', to='TOOLS.lokalizacja'),
        ),
        migrations.AddField(
            model_name='narzedziemagazynowe',
            name='ostatni_dostawca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narzedzia_dostarczane', to='TOOLS.dostawca'),
        ),
        migrations.AddField(
            model_name='narzedziemagazynowe',
            name='podkategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narzedzia', to='TOOLS.podkategoria'),
        ),
        migrations.AddField(
            model_name='historiauzycianarzedzia',
            name='egzemplarz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='TOOLS.egzemplarznarzedzia'),
        ),
        migrations.AddField(
            model_name='historiauzycianarzedzia',
            name='maszyna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historia_uzycia', to='TOOLS.maszyna'),
        ),
        migrations.AddField(
            model_name='historiauzycianarzedzia',
            name='pracownik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historia_uzycia', to='TOOLS.pracownik'),
        ),
        migrations.AddField(
            model_name='fakturazakupu',
            name='dostawca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faktury', to='TOOLS.dostawca'),
        ),
        migrations.AlterField(
            model_name='egzemplarznarzedzia',
            name='faktura_zakupu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egzemplarze', to='TOOLS.fakturazakupu'),
        ),
        migrations.AlterField(
            model_name='egzemplarznarzedzia',
            name='narzedzie_typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egzemplarze', to='TOOLS.narzedziemagazynowe'),
        ),
        migrations.DeleteModel(
            name='Faktura',
        ),
        migrations.DeleteModel(
            name='Narzedzie',
        ),
    ]
