# Generated by Django 4.2.23 on 2025-11-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0018_fakturazakupu_historiauzycianarzedzia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egzemplarznarzedzia',
            name='zamowienie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egzemplarze', to='TOOLS.zamowienie'),
        ),
        migrations.AddField(
            model_name='narzedziemagazynowe',
            name='ilosc_w_opakowaniu',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='narzedziemagazynowe',
            name='opakowanie',
            field=models.CharField(choices=[('szt', 'Sztuka'), ('kompl', 'Komplet')], default='szt', max_length=10),
        ),
    ]
