# Generated by Django 4.2.23 on 2025-11-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0019_egzemplarznarzedzia_zamowienie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egzemplarznarzedzia',
            name='stan',
            field=models.CharField(choices=[('nowe', 'Nowe'), ('uzywane', 'Używane'), ('uszkodzone', 'Uszkodzone'), ('uszkodzone_regeneracja', 'Uszkodzone do regeneracji')], default='nowe', max_length=30),
        ),
    ]
