# Generated by Django 4.2.23 on 2026-03-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0041_add_reczna_kontrola_fields'),
    ]

    operations = [
        # 1. Zrzuć NOT NULL i zmień default — pozwól na NULL w CharField
        migrations.RunSQL(
            sql='ALTER TABLE "TOOLS_uszkodzenie" ALTER COLUMN stracony_czas DROP NOT NULL;',
            reverse_sql='ALTER TABLE "TOOLS_uszkodzenie" ALTER COLUMN stracony_czas SET NOT NULL;',
        ),
        # 2. Konwertuj tekstowe wartości na czyste liczby, puste/brak-liczb na NULL
        migrations.RunSQL(
            sql="""
                UPDATE "TOOLS_uszkodzenie"
                SET stracony_czas = CASE
                    WHEN stracony_czas ~ '\\d+' THEN regexp_replace(stracony_czas, '[^0-9]', '', 'g')
                    ELSE NULL
                END;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 3. Zmień typ kolumny na INTEGER
        migrations.AlterField(
            model_name='uszkodzenie',
            name='stracony_czas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
