# Generated by Django 4.2.23 on 2026-03-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0042_change_stracony_czas_to_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycjazapotrzebowania',
            name='w_zamowieniu',
            field=models.BooleanField(default=False, help_text='Czy pozycja trafiła do generatora zamówień'),
        ),
    ]
