# Generated by Django 4.2.23 on 2026-03-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0043_add_w_zamowieniu_to_pozycja_zapotrzebowania'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycjageneratora',
            name='zrodlo',
            field=models.CharField(default='auto', help_text='Źródło pozycji: auto, reczne, zapotrzebowanie', max_length=50),
        ),
        migrations.AddField(
            model_name='pozycjageneratora',
            name='zrodlo_zapotrzebowanie_ids',
            field=models.CharField(blank=True, help_text='ID zapotrzebowań (ZAM-XXXX) — jeśli źródło=zapotrzebowanie', max_length=200),
        ),
        migrations.AlterField(
            model_name='zapotrzebowanietechnologa',
            name='status',
            field=models.CharField(choices=[('draft', 'Robocze'), ('submitted', 'Wysłane'), ('completed', 'Zrealizowane'), ('ordered', 'W zamówieniu'), ('cancelled', 'Anulowane')], default='draft', max_length=20),
        ),
    ]
