# Generated by Django 4.2.23 on 2026-05-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0050_kategoria_grupa_stanowiska'),
    ]

    operations = [
        migrations.AddField(
            model_name='dostawca',
            name='generuj_csv',
            field=models.BooleanField(default=False, help_text='Jeśli zaznaczone, do emaila z zamówieniem dla tego dostawcy dołączany jest plik CSV (separator "|").', verbose_name='Generuj plik CSV'),
        ),
        migrations.CreateModel(
            name='NumerKatalogowyDostawcy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_katalogowy_dostawcy', models.CharField(max_length=100, verbose_name='Nr katalogowy u dostawcy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dostawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numery_katalogowe_narzedzi', to='TOOLS.dostawca')),
                ('narzedzie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numery_dostawcow', to='TOOLS.narzedziemagazynowe')),
            ],
            options={
                'verbose_name': 'Numer katalogowy dostawcy',
                'verbose_name_plural': 'Numery katalogowe dostawców',
                'ordering': ['dostawca__nazwa_firmy', 'narzedzie__numer_katalogowy'],
                'unique_together': {('narzedzie', 'dostawca')},
            },
        ),
    ]
