# Generated by Django 4.2.23 on 2026-05-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0051_dostawca_csv_i_mapowania'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='nr_oferty_dostawcy',
            field=models.CharField(blank=True, default='', help_text='Nr oferty dostawcy, na podstawie której składane jest zamówienie (widoczny tylko dla logistyki)', max_length=100),
        ),
    ]
