# Generated by Django 4.2.23 on 2026-05-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0052_zamowienie_nr_oferty_dostawcy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='karta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nr karty'),
        ),
    ]
