# Generated by Django 4.2.23 on 2026-06-07 14:34

from django.db import migrations, models


def oznacz_ceny_z_zamowien(apps, schema_editor):
    """Oznacza istniejące ceny pochodzące z zamówień (propagacja działała od migracji 0048).

    Heurystyka jak w backfill_cena_jednostkowa: cena narzędzia równa cenie najnowszej
    pozycji zamówienia → wyliczona. Pozostałe (ręczne, zerowe, bez historii) → False.
    """
    NarzedzieMagazynowe = apps.get_model('TOOLS', 'NarzedzieMagazynowe')
    PozycjaZamowienia = apps.get_model('TOOLS', 'PozycjaZamowienia')

    for narzedzie in NarzedzieMagazynowe.objects.exclude(cena_jednostkowa__isnull=True).iterator():
        poz = (
            PozycjaZamowienia.objects
            .filter(narzedzie_typ_id=narzedzie.id, cena_jednostkowa__isnull=False)
            .order_by('-zamowienie__data_utworzenia', '-id')
            .first()
        )
        if poz is not None and poz.cena_jednostkowa == narzedzie.cena_jednostkowa:
            narzedzie.cena_z_zamowienia = True
            narzedzie.save(update_fields=['cena_z_zamowienia'])


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0053_pracownik_karta_remove_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='narzedziemagazynowe',
            name='cena_z_zamowienia',
            field=models.BooleanField(default=False, help_text='Cena nadpisana automatycznie z pozycji zamówienia.', verbose_name='Cena wyliczona z zamówień'),
        ),
        migrations.RunPython(oznacz_ceny_z_zamowien, migrations.RunPython.noop),
    ]
