# Generated by Django 4.2.23 on 2026-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOLS', '0054_narzedziemagazynowe_cena_z_zamowienia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycjazapotrzebowania',
            name='opakowanie',
            field=models.CharField(choices=[('szt', 'Sztuka'), ('kompl', 'Komplet')], default='szt', max_length=20),
        ),
    ]
